[package]
name = "wrym"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "wrym_udp",
    "wrym_webtransport"
]

[dependencies]
async-trait = "0.1.86"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
wrym_udp = { path = "wrym_udp" }
wrym_webtransport = { path = "wrym_webtransport" }
