[package]
name = "wrym"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "wrym_udp",
    "wrym_webtransport",
    "wrym_laminar"
]
resolver = "2"

[dependencies]
async-trait = "0.1.86"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "io-std"] }
wrym_udp = { path = "wrym_udp" }
wrym_webtransport = { path = "wrym_webtransport" }
wrym_laminar = { path = "wrym_laminar" }
bincode = "1.3.3"
