[package]
name = "wrym"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
mio = { version = "1.0.3", features = ["os-poll", "net"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "sync", "macros", "time"]}
