[package]
name = "wrym"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
