[package]
name = "wrym_webtransport"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"]}
wtransport = "0.5.0"

wrym_transport = { path = "../wrym_transport" }